'use client'
import { useRouter } from 'next/navigation'
import { companyStatistic } from '../assets/data/company-statistic'
import Container from '../components/container/Container'
import Heading from '../components/heading/Heading'
import { ChevronIcon, CopyIcon, PlusIcon } from '../components/icons'
import Button from '../components/ui/Button'
import ButtonIcon from '../components/ui/ButtonIcon'
import { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerTitle, DrawerTrigger } from '../components/ui/Drawer'
import { Field, FieldDescription, FieldLabel } from '../components/ui/Field'
import { Input } from '../components/ui/Input'
import { handleCopy } from '../utils/copy-text'
import { PUBLIC_URL } from '../config/url.config'

export default function PartnersPage() {
	const router = useRouter()
	const siteUrl = 'https://utms.pro/test/test/test'
	return (
		<div className='flex flex-col min-h-screen overflow-hidden'>
			<Container>
				<div className='py-4 flex flex-col gap-6'>
					<div className='flex items-center justify-between gap-3'>
						<Heading className='text-nowrap text-ellipsis overflow-hidden'>My company</Heading>
						<Drawer>
							<DrawerTrigger>
								<Button size='meduim' variant='primary' as='div'>
									<PlusIcon />
									<span>Add</span>
								</Button>
							</DrawerTrigger>
							<DrawerContent>
								<DrawerHeader>
									<DrawerTitle>
										New Campaign
									</DrawerTitle>
									<DrawerDescription>Set up the settings for your future advertising campaign.</DrawerDescription>
								</DrawerHeader>
								<Container>
									<form className='flex flex-col gap-6'>
										<Field>
											<FieldLabel htmlFor="company-name">
												Name
											</FieldLabel>
											<Input
												id="company-name"
												placeholder="Issue #777"
												required
											/>
											<FieldDescription>
												All transactions are secure and encrypted
											</FieldDescription>
										</Field>
										<Field>
											<FieldLabel htmlFor="partner-ship">
												Partnership Model
											</FieldLabel>
											<Input
												id="partner-ship"
												placeholder="RevShare 25%"
												required
											/>
											<FieldDescription>
												From the casino’s profit generated by each referred user, a 25% commission will be credited to you — permanently.
											</FieldDescription>
										</Field>
									</form>
								</Container>
								<DrawerFooter className='flex-row'>
									<DrawerClose className='flex-1'>
										<Button as='div' className='w-full'>Cancel</Button>
									</DrawerClose>
									<Button variant='primary' className='flex-1'>Create</Button>
								</DrawerFooter>
							</DrawerContent>
						</Drawer>
					</div>
					<div className='flex flex-col gap-2'>
						<div className='py-3 px-4 grid grid-cols-[6.4375rem_1fr] uppercase text-text text-xs'>
							<span>NAME & DATE</span>
							<span>REVENUE & LINK</span>
						</div>
						<div className='rounded-[1rem] bg-buttons py-3 px-4 grid grid-cols-[6.4375rem_1fr] leading-none'>
							<div>
								<div className='text-sm font-black h-5'>Company 1</div>
								<div className='text-sm text-text font-semibold h-6 flex items-center'>
									18.12.2025
								</div>
							</div>
							<div className='flex items-center overflow-hidden'>
								<div className='pr-5 flex-1 overflow-hidden'>
									<div className='text-sm font-black h-5 px-1  bg-buttons w-fit rounded-full'>$0.00</div>
									<div className='text-sm text-text font-semibold h-6 flex items-center gap-2'>
										<span className='text-ellipsis overflow-hidden flex-1'>
											{siteUrl}
										</span>
										<ButtonIcon
											size='small'
											icon={<CopyIcon />}
											onClick={() => handleCopy(siteUrl)}
										/>
									</div>
								</div>
								<div className='w-4 h-4 flex items-center justify-center shrink-0 -rotate-90 opacity-50'
									onClick={() => router.push(PUBLIC_URL.partners('/company'))}
								><ChevronIcon size={12} /></div>
							</div>
						</div>
					</div>
					<div className='flex flex-col gap-4'>
						<Heading size='medium' as='h3'>Statistics</Heading>
						<div>
							{companyStatistic.map((statisticRow, index) => (
								<div className='py-4 border-b border-buttons leading-none grid gap-1.5 first:pt-0 last:pb-0 last:border-none' key={index}>
									{statisticRow.map(statisticItem => (
										<div className='flex items-center justify-between text-nowrap text-sm gap-3' key={statisticItem.title}>
											<span className='text-ellipsis flex-1 overflow-hidden font-semibold text-text'>
												{statisticItem.title}
											</span>
											<span className='font-black'>{statisticItem.counter}</span>
										</div>
									))}
								</div>
							))}
							<div className='py-4 border-b border-buttons leading-none grid gap-1.5 first:pt-0 last:pb-0 last:border-none' >
								<div className='flex items-center justify-between text-nowrap text-sm gap-3' >
									<span className='text-ellipsis flex-1 overflow-hidden font-semibold text-text'>
										Total Revenue
									</span>
									<span className='font-black'>$13,357</span>
								</div>

							</div>
						</div>
					</div>
				</div>
			</Container>
		</div>
	)
}
